# Do not change this value as it might end up in a plugin that does not work
config-version: 1.0.1

# This is the interval for when a sell chest should sell its contents
# For example, you can use '1d 2h 3m 4s' where the interval then would be 1 day, 2 hours, 3 minutes and 4 seconds
autosell-interval: "10m"
# Note: This plugin isn't tested on servers with over 200+ players, we do not recommend using a short interval if you do not have the resources for this!

# By default players can actively use 5 sell chests, but this can be overriden using permissions
# Example: Players with permission 'autosellchests.maxchests.donator' will be able to use 15 sell chests at a time
# A player that has two or more overrides(permissions), will use the highest value
max-sellchests:
  default: 5
  override:
    vip: 10
    donator: 15
    devs: 20


# Whether the owner of the chest needs to be online for the chest to sell its contents
online-chest-owner: true
# Warning: Chests that are in unloaded chunks will get loaded by the plugin when this setting is 'false' which can cause server lag,
# ALSO note that permissions for selling items to shop will not be checked, NOR item discounts + any sell multipliers when the player is offline

# The title/item name of a sell chest
sellchest-name: "&7&lSell chest"

# The default chest name for displaying in chat, ...
# The chest name can be changed in chest settings
# Using '%id%' you can get the sell chest ID
default-chest-name: "#FF7070Sell#CDCDCDChest"

# The lore of a sell chest item
sellchest-lore:
  - "&cThis chest sells its contents"
  - "&cautomatically every &e%interval%"
  - "&aPlace this chest down and"
  - "&aleft-click it to get more info"

# A visual effect shown to the player when they place a sell chest,
# this is additional to the message that is sent to the player that shows the maximum amount of chests they have placed/can place
# Available options are: 'NONE', 'BOSS_BAR' and 'ACTION_BAR'
chest-confirmation-effect: BOSS_BAR

# Additionally you can set the boss bar color
# Available colors are 'PINK', 'BLUE', 'RED', 'GREEN', 'YELLOW', 'PURPLE' and 'WHITE'
chest-confirmation-boss-bar-color: GREEN

# The sound effects played when a player places/breaks a SellChest
# You can visit this page for all available sound effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# To disable a sound effect you can empty out the string like ""
sound-effects:
  volume: 1
  pitch: 1
  pickup-chest: "ENTITY_ENDERMAN_TELEPORT"
  place-chest: "ENTITY_SPLASH_POTION_BREAK"

# Controls settings for when the plugin should log sell intervals to console
# If no interval has been set and this option is enabled, the plugin will log after each sell chest sells its contents
interval-logs:
  # Enable or disable interval logging completely
  enable: true
  # Set the interval for when the plugin should log to console
  interval: 10m

# Enable or disable messages send to player when their sell chest has sold items
sold-items-logging-player: true
# This setting is also configurable per chest in the settings menu,
# but when this option is disabled, it will override the per chest setting

# Enable or disable messages send to console for when any sell chest has sold items
sold-items-logging-console: false

# The fill item which fills empty spots inside any GUI
fill-item:
  material: GRAY_STAINED_GLASS_PANE
  name: " "

# Compatibility mode enables support for chests which are created before plugin version v2.4.0
# Do not enable this option for any other reason, there is a reason this is disabled by default.
compatibility-mode: false

# Debug mode logs extra messages to console for better debugging
debug: false