# Do not change this value as it might end up in a plugin that does not work
config-version: 1.0.2

# This is the interval for when a sell chest should sell its contents
# For example, you can use '1d 2h 3m 4s' where the interval then would be 1 day, 2 hours, 3 minutes and 4 seconds
autosell-interval: "10m"

# When disabled, the option to upgrade chests is disabled and all chests will behave the same
enable-interval-upgrades: true

# The list of upgrades where the first upgrade in this track is always the default upgrade for new chests
interval-upgrades:
  lvl1:
    # The upgrade item
    item: COAL
    # The weight of the level, where the smallest weight represents first level
    weight: 10
    price: 0
    # The upgrade name
    name: "&7&lInterval level &f&lI"
    # The lore of the upgrade item
    lore:
    - "&aClick to upgrade to &e&llevel &f&l(II)"
    - " "
    - "&8Upgrade info:"
    - "&8Sell interval: &f&m5m&r &f2m"
    - "&8Cost: &f$15000"
    # Whether the item should have a enchantment glint
    enchanted: true
    # The sell interval of chests in this upgrade
    interval: "5m"

  lvl2:
    item: IRON_INGOT
    weight: 20
    # The price of this upgrade
    # If no direct currency has been specified, it will use the default currency in EconomyShopGUI
    # It is possible to specify a direct currency like GEMS_ECONOMY:2000, but requires the currency to be registered within EconomyShopGUI
    price: 15000
    name: "&7&lInterval level &f&lII"
    lore:
      - "&aClick to upgrade to &e&llevel &f&l(III)"
      - " "
      - "&8Upgrade info:"
      - "&8Sell interval: &f&m2m&r &f1m"
      - "&8Cost: &f35000"
    enchanted: true
    interval: "2m"

  lvl3:
    item: GOLD_INGOT
    weight: 30
    price: 35000
    name: "&7&lInterval level &f&lIII"
    lore:
      - "&aClick to upgrade to &e&llevel &f&l(IV)"
      - " "
      - "&8Upgrade info:"
      - "&8Sell interval: &f&m1m&r &f30s"
      - "&8Cost: &f$60000"
    enchanted: true
    interval: "1m"

  lvl4:
    item: DIAMOND
    weight: 40
    price: 60000
    name: "&7&lInterval level &f&l(IV)"
    lore:
      - "&cAlready at max level, cannot upgrade again."
    enchanted: true
    interval: "30s"

# By default players can actively use 5 sell chests, but this can be overriden using permissions
# Example: Players with permission 'autosellchests.maxchests.donator' will be able to use 15 sell chests at a time
# A player that has two or more overrides(permissions), will use the highest value
max-sellchests:
  default: 5
  override:
    vip: 10
    donator: 15
    devs: 20


# Whether the owner of the chest needs to be online for the chest to sell its contents
online-chest-owner: true
# Note that permissions for selling items to shop will not be checked, NOR item discounts + any sell multipliers when the player is offline
# Also note that this plugin will not load chunks, meaning if the sell chest is located in a unloaded chunk, the plugin will skip that chest


# AFK Prevention
# When enabled, this prevents sell chests to sell whenever the owner is AFK
afk-prevention: false
# Note: currently AFK is detected by CMI or Essentials

# The title/item name of a sell chest
sellchest-name: "&7&lSell chest"

# The default chest name for displaying in chat, ...
# The chest name can be changed in chest settings
# Using '%id%' you can get the sell chest ID
default-chest-name: "#FF7070Sell#CDCDCDChest"

# The lore of a sell chest item
sellchest-lore:
  - "&cThis chest sells its contents"
  - "&cautomatically every &e%interval%"
  - "&aPlace this chest down and"
  - "&aleft-click it to get more info"

# A visual effect shown to the player when they place a sell chest,
# this is additional to the message that is sent to the player that shows the maximum amount of chests they have placed/can place
# Available options are: 'NONE', 'BOSS_BAR' and 'ACTION_BAR'
chest-confirmation-effect: BOSS_BAR

# Additionally you can set the boss bar color
# Available colors are 'PINK', 'BLUE', 'RED', 'GREEN', 'YELLOW', 'PURPLE' and 'WHITE'
chest-confirmation-boss-bar-color: GREEN

# The sound effects played when a player places/breaks a SellChest
# You can visit this page for all available sound effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# To disable a sound effect you can empty out the string like ""
sound-effects:
  volume: 1
  pitch: 1
  pickup-chest: "ENTITY_ENDERMAN_TELEPORT"
  place-chest: "ENTITY_SPLASH_POTION_BREAK"

# Controls settings for when the plugin should log sell intervals to console
# If no interval has been set and this option is enabled, the plugin will log after each sell chest sells its contents
interval-logs:
  # Enable or disable interval logging completely
  enable: true
  # Set the interval for when the plugin should log to console
  interval: 10m

# Enable or disable messages send to player when their sell chest has sold items
sold-items-logging-player: true
# This setting is also configurable per chest in the settings menu,
# but when this option is disabled, it will override the per chest setting

# The fill item which fills empty spots inside any GUI
fill-item:
  material: GRAY_STAINED_GLASS_PANE
  name: " "

# Compatibility mode enables support for chests which are created before plugin version v2.4.0
# Do not enable this option for any other reason, there is a reason this is disabled by default.
compatibility-mode: false

# Debug mode logs extra messages to console for better debugging
debug: false