# Do not change this value as it might end up in a plugin that does not work
config-version: 1.0.0

# This is the interval for when a sell chest should sell its contents
# For example, you can use '1d 2h 3m 4s' where the interval then would be 1 day, 2 hours, 3 minutes and 4 seconds
autosell-interval: "10m"
# Note: This plugin isn't tested on servers with over 200+ players, we do not recommend using a short interval if you do not have the resources for this!

# Maximum amount of sell chests a player can actively use
player-max-sellchests: 5

# Whether the owner of the chest needs to be online for the chest to sell its contents
online-chest-owner: true
# Warning: Chests that are in unloaded chunks will get loaded by the plugin when this setting is 'false' which can cause server lag,
# ALSO note that permissions for selling items to shop will not be checked, NOR item discounts + any sell multipliers

# The title/item name of a sell chest
sellchest-name: "&7&lSell chest"

# The default chest name for displaying in chat, ...
# The chest name can be changed in chest settings
# Using '%id%' you can get the sell chest ID
default-chest-name: "#FF7070Sell#CDCDCDChest"

# The lore of a sell chest item
sellchest-lore:
  - "&cThis chest sells its contents"
  - "&cautomatically every &e%interval%"
  - "&aPlace this chest down and"
  - "&aleft-click it to get more info"

# A visual effect shown to the player when they place a sell chest,
# this is additional to the message that is sent to the player that shows the maximum amount of chests they have placed/can place
# Available options are: 'NONE', 'BOSS_BAR' and 'ACTION_BAR'
chest-confirmation-effect: BOSS_BAR

# Additionally you can set the boss bar color
# Available colors are 'PINK', 'BLUE', 'RED', 'GREEN', 'YELLOW', 'PURPLE' and 'WHITE'
chest-confirmation-boss-bar-color: GREEN

# The sound effects played when a player places/breaks a SellChest
# You can visit this page for all available sound effects: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# To disable a sound effect you can empty out the string like ""
sound-effects:
  volume: 1
  pitch: 1
  pickup-chest: "ENTITY_ENDERMAN_TELEPORT"
  place-chest: "ENTITY_SPLASH_POTION_BREAK"

# Enable or disable messages send to console for when the sell interval completes
sell-interval-logging: false

# Enable or disable messages send to player when their sell chest has sold items
sold-items-logging-player: true
# This setting is also configurable per chest in the settings menu,
# but when this option is disabled, it will override the per chest setting

# Enable or disable messages send to console for when any sell chest has sold items
sold-items-logging-console: false

# Debug mode logs extra messages to console for better debugging
debug: false

# The tier list for different kind of sell chests using a custom sell multiplier
# When the 'upgradeable' setting is enabled, players will be able to upgrade the chest tier using ingame money
chest-tiers:
  enabled: true
  upgradeable: false
  tier-track:
    1:
      displayname: "&6&lTier &f&lI"
      multiplier: 0
    2:
      displayname: "&6&lTier &f&lII"
      multiplier: 2.5
      cost: 5000
    3:
      displayname: "&6&lTier &f&lIII"
      multiplier: 5
      cost: 10000
    4:
      displayname: "&6&lTier &f&lIV"
      multiplier: 10
      cost: 20000
    5:
      displayname: "&6&lTier &f&lV"
      multiplier: 15
      cost: 35000