name: AutoSellChests
version: '2.3.0'
main: me.gypopo.autosellchests.AutoSellChests
description: A addon for EconomyShopGUI which uses custom chests to automatically sell its contents to shop
api-version: '1.19'
has-open-classloader: true

dependencies:
  - name: EconomyShopGUI
    required: false
    bootstrap: false
  - name: EconomyShopGUI-Premium
    required: false
    bootstrap: false

permissions:
  autosellchests.use:
    default: true
    description: "Allows to use the /autosellchests command"
  autosellchests.place:
    default: true
    description: "Allows to place a sell chest"
  autosellchests.pickup:
    default: true
    description: "Allows to pick up your own sell chest"
  autosellchests.show.all:
    description: "Allows to view info of a SellChest from a different player"
  autosellchests.maxchests.override:
    description: "Allows to place an infinite amount of chests"
  autosellchests.break:
    description: "Allows to break someone else chest"
  autosellchests.give:
    description: "Gives access to the /asc give command"
  autosellchests.view:
    description: "Gives access to the /asc view command"
  autosellchests.reload:
    description: "Gives access to the /asc reload command"
  autosellchests.remove:
    description: "Gives access to the /asc remove command"