name: AutoSellChests
version: 1.0.6
main: me.gypopo.autosellchests.AutoSellChests
api-version: 1.16
authors: [ Gypopo ]
description: A addon for EconomyShopGUI which uses custom chests to automatically sell its contents to shop
commands:
  autosellchests:
    usage: /asc <subcommand> <args>
    aliases: [asc]

softdepend:
  - EconomyShopGUI
  - EconomyShopGUI-Premium
