# This is the interval for when a sell chest should sell its contents
# For example, you can use '1d 2h 3m 4s' where the interval then would be 1 day, 2 hours, 3 minutes and 4 seconds
autosell-interval: "10m"
# Note: This plugin isn't tested on servers with over 200+ players, we do not recommend using a short interval if you do not have the resources for this!

# Maximum amount of sell chests a player can place
player-max-sellchests: 5

# The title/item name of a sell chest
sellchest-name: "&7&lSell chest"

# The lore of a sell chest item
sellchest-lore:
  - "&cThis chest sells its contents"
  - "&cautomatically every &e%interval%"
  - "&aPlace this chest down and"
  - "&aright-click it to get more info"

# Enable or disable messages send to player when their sell chest has sold items
sold-items-logging-player: true

# Enable or disable messages send to console for when any sell chest has sold items
sold-items-logging-console: true

# Debug mode logs extra messages to console for better debugging
debug: false